CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    codigo VARCHAR(50),
    descricao TEXT,
    preco_venda NUMERIC(10,2) NOT NULL,
    quantidade_estoque INTEGER NOT NULL,
    categoria_id BIGINT REFERENCES categorias(id),
    version BIGINT NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda TIMESTAMP NOT NULL,
    valor_total NUMERIC(10,2) NOT NULL,
    cliente_id BIGINT REFERENCES clientes(id),
    forma_pagamento VARCHAR(30),
    desconto NUMERIC(10,2) DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVA',
    data_cancelamento TIMESTAMP,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS itens_venda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id BIGINT NOT NULL REFERENCES vendas(id),
    produto_id BIGINT NOT NULL REFERENCES produtos(id),
    quantidade INTEGER NOT NULL,
    preco_unitario NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS despesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    valor NUMERIC(10,2) NOT NULL,
    data_pagamento DATE NOT NULL,
    categoria VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    forma_pagamento VARCHAR(30),
    observacoes TEXT,
    parcelas INTEGER NOT NULL DEFAULT 1,
    parcela_atual INTEGER NOT NULL DEFAULT 1,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

ALTER TABLE produtos ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ATIVA';
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS data_cancelamento TIMESTAMP;
UPDATE vendas SET status = 'ATIVA' WHERE status IS NULL;

CREATE INDEX IF NOT EXISTS idx_produtos_ativos_nome ON produtos (ativo, nome);
CREATE INDEX IF NOT EXISTS idx_produtos_codigo ON produtos (codigo);
CREATE INDEX IF NOT EXISTS idx_vendas_data ON vendas (data_venda);
CREATE INDEX IF NOT EXISTS idx_vendas_status_data ON vendas (status, data_venda);
CREATE INDEX IF NOT EXISTS idx_despesas_ativo_data ON despesas (ativo, data_pagamento);
CREATE INDEX IF NOT EXISTS idx_despesas_status ON despesas (status);
CREATE INDEX IF NOT EXISTS idx_itens_venda_venda ON itens_venda (venda_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_produtos_estoque_nao_negativo') THEN
        ALTER TABLE produtos ADD CONSTRAINT ck_produtos_estoque_nao_negativo
            CHECK (quantidade_estoque >= 0) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_produtos_preco_positivo') THEN
        ALTER TABLE produtos ADD CONSTRAINT ck_produtos_preco_positivo
            CHECK (preco_venda > 0) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_vendas_desconto_nao_negativo') THEN
        ALTER TABLE vendas ADD CONSTRAINT ck_vendas_desconto_nao_negativo
            CHECK (desconto >= 0) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_despesas_valor_positivo') THEN
        ALTER TABLE despesas ADD CONSTRAINT ck_despesas_valor_positivo
            CHECK (valor > 0) NOT VALID;
    END IF;
END $$;
