CREATE TABLE IF NOT EXISTS movimentacoes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL REFERENCES produtos(id),
    venda_id BIGINT REFERENCES vendas(id),
    tipo VARCHAR(30) NOT NULL,
    quantidade INTEGER NOT NULL,
    saldo_anterior INTEGER NOT NULL,
    saldo_posterior INTEGER NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    data_movimentacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_movimentacoes_produto_data
    ON movimentacoes_estoque (produto_id, data_movimentacao DESC);
CREATE INDEX IF NOT EXISTS idx_movimentacoes_venda
    ON movimentacoes_estoque (venda_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_movimentacoes_saldo') THEN
        ALTER TABLE movimentacoes_estoque ADD CONSTRAINT ck_movimentacoes_saldo
            CHECK (saldo_posterior - saldo_anterior = quantidade);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_itens_venda_quantidade_positiva') THEN
        ALTER TABLE itens_venda ADD CONSTRAINT ck_itens_venda_quantidade_positiva
            CHECK (quantidade > 0) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_itens_venda_preco_positivo') THEN
        ALTER TABLE itens_venda ADD CONSTRAINT ck_itens_venda_preco_positivo
            CHECK (preco_unitario > 0) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_vendas_total_nao_negativo') THEN
        ALTER TABLE vendas ADD CONSTRAINT ck_vendas_total_nao_negativo
            CHECK (valor_total >= 0) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_despesas_parcelas_positivas') THEN
        ALTER TABLE despesas ADD CONSTRAINT ck_despesas_parcelas_positivas
            CHECK (parcelas > 0 AND parcela_atual > 0 AND parcela_atual <= parcelas) NOT VALID;
    END IF;
END $$;
