spring.application.name=api

# === Datasource PostgreSQL ===
spring.datasource.url=jdbc:postgresql://ep-odd-union-acv1f5tz-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_kOHY6yMq4zgh
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA (Para criar as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

